### ISSUE TITLE
sample-data/data.yaml should have API examples

### ISSUE THREAD

**Issue by ultrasaurus** [18F/open-data-maker#171]
it's supported by the app, but I never added it to sample data
```
examples:
- name: Chicago
  description: all of the data for a city by a specific name
  params: name=Chicago
- name: Multiple Values
  description: all of the cities in New York and Massachusetts
  params: state=NY,MA
- name: Partial Data
  description: all of the cities in California, but only return name and size
  params: state=CA&fields=name,size
```
