### ISSUE TITLE
JSON output: need configuration for types

### ISSUE THREAD

**Issue by shawnbot** [18F/open-data-maker#8]
A couple of notes on JSON output:

- [x] We should serve responses with the appropriate [MIME type](https://en.wikipedia.org/wiki/JSON#MIME_type): `application/json`.
- [x] It should be possible to declare columns as numeric so that they can be rendered as such in JSON, rather than everything being strings. This can get a little funky with floats, so it may be necessary to tweak whatever JSON serializer we're using to limit float precision (to, say, two decimal places).

Proposal for a data dictionary in data.yaml that specifies types (and other things):

```
data_dictionary:
  year:   # column created via 'add' directive in files section, source is not required
    type: integer
  state: 
    source: USPS
    description: Two character abbreviation for State or US Territory
    type: string
    title: State or US Territory
  name: CITNM      # default to string
  region_id: 
    source: REGID 
    description: Deptartment of Interior standard region identifier
    type: integer
    title: Region ID
    range: 0..8
  population:
    source: POP10
    type: integer
  location:
    source: 
      lat: INTPTLAT
      lon: INTPTLONG
    type: location
  somelistofnumbers:
    source: [NUM25, NUM50, NUM75]
    type: float
```
